#!/bin/sh


echo "[stage 1] mounting filesystems..."
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
mount -t tmpfs tmpfs /run
mkdir -p /run/udev

echo "[stage 1] setting hostname..."
hostname -F /etc/hostname

for type in rsa ecdsa ed25519; do
    if [ ! -f /etc/ssh/ssh_host_${type}_key ]; then
        ssh-keygen -t $type -f /etc/ssh/ssh_host_${type}_key -N ""
    fi
done

export SVDIR=/etc/sv

echo "[stage 1] bringing up loopback..."
ip link set lo up

# Register sysroot packages in flux database on first boot
/usr/bin/flux-bootstrap.sh

echo "[stage 1] done"