#!/bin/sh


echo "[stage 1] mounting filesystems..."
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
mount -t tmpfs tmpfs /run
mkdir -p /run/udev

echo "[stage 1] setting hostname..."
hostname -F /etc/hostname

export SVDIR=/etc/sv

echo "[stage 1] bringing up loopback..."
ip link set lo up

echo "[stage 1] done"