#!/bin/sh
echo "[stage 2] triggering udev input devices..."
udevadm trigger --action=add --subsystem-match=input
udevadm settle

echo "[stage 2] starting service supervision..."
exec runsvdir /etc/sv
