#!/bin/sh
sleep 5
find /sys/devices -name "event*" -path "*/input/event*" | while read dev; do
    parent=$(dirname "$dev")
    udevadm test "$parent" > /dev/null 2>&1
done
touch /etc/sv/udev-input-trigger/down