#!/bin/sh
sleep 5
find /sys/devices -path "*/input/input*/event*" -type d | while read dev; do
    parent=$(dirname "$dev")
    udevadm test "$parent" > /dev/null 2>&1
done
touch /etc/sv/udev-input-trigger/down