#!/bin/sh
export HOME=/root
export USER=root
export XDG_RUNTIME_DIR=/run/user/0
export LIBSEAT_BACKEND=seatd
mkdir -p "$XDG_RUNTIME_DIR"
chmod 700 "$XDG_RUNTIME_DIR"

i=0
while [ ! -S /run/seatd.sock ] && [ $i -lt 30 ]; do
    sleep 1
    i=$((i + 1))
done

exec /usr/bin/kira-start-swayFX > /tmp/swayfx.log 2>&1